### ISSUE TITLE
Trade failure

### ISSUE THREAD

**Issue by Sharingisnotillegal** [TastyLollipop/OpenWorld#10] opened 2022-03-16 00:47 UTC
https://gist.github.com/9f0873002775326d95281de85298c75f Recipients side
https://gist.github.com/HugsLibRecordKeeper/7a9269087a361ce2a74611e6a305515a Sender side
Expected behavior:
Chinchilla corpse gets placed on persons plot

Actual behavior:
Chinchilla does not exist anymore

Steps:
Doublecheck both are online
Start trade
Ask for 1 silver, send one dead rotten chinchilla
Info appears on recipients monitor that it will appear in center of map.
Nothing happens.

Line on recipients side: 292
Corpse_Chinchilla62394 spawned in bugged state. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Please note that it looks like some kind of disconnect also happened right after this trade, but unable to really report that as a bug as i dont know what happened and not been reproduced and did not see clearly when it happened.(sender side)

Version server: 1.2
Client Auto from workshop/Capitalism

**Comment by Sharingisnotillegal** [comment] 2022-03-24 20:56
https://gist.github.com/d2cfeb506fbc78ed94e0bc55b7a67d42 (sender side)
https://gist.github.com/84f26520d9bb32359342faa9dd2ddaf6 (receiver side, logs after relogged)

Occurred again, Secrecy version both, version 1.2.3 server.
Server console says: 
[3/24/2022 8:14:19 PM] │ Client [Windows95] [109.78.92.31] Has Connected
[3/24/2022 8:14:50 PM] │ Client [hej] [84.217.24.135] Has Connected
[3/24/2022 9:45:39 PM] │ Client [Windows95] [109.78.92.31] Has Connected
[3/24/2022 9:45:39 PM] │ Player [Windows95] Has Disconnected
[3/24/2022 9:51:54 PM] │ Gift Done Between [Windows95] And [hej]
[3/24/2022 9:52:16 PM] │ Player [hej] Has Disconnected
[3/24/2022 9:52:40 PM] │ Client [hej] [84.217.24.135] Has Connected

This time around it looks like i got disconnected, but it still allowed me to trade [?]

**Comment by ghost** [comment] 2022-11-23 21:05
Closing issue as the problem is very old, going to remake the whole item transfer system to prevent this kind of issues

**Closed as completed by ghost** 2022-11-23 21:05 UTC
